repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=300']
      - id: check-merge-conflict
      - id: check-ast # checks python syntax tree for errors
      - id: debug-statements
      - id: check-yaml # checks .yaml for errors
        args: ['--unsafe'] # Instead of loading the files, simply parse them for syntax.
        exclude: 'staged_variables.yaml'
      - id: check-toml # checks .toml for errors
      - id: check-xml # checks .xml for errors
      - id: detect-aws-credentials # detects aws cred
      - id: detect-private-key # detects private keys
      - id: requirements-txt-fixer # fixes requirements txt and sorts it

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        entry: ruff check
        args:
          - --select
          - I
          - --fix
        types_or: [ python, pyi, jupyter ]
      - id: ruff
        entry: ruff check
        args:
          - --fix
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
#      - id: cargo-check
#      - id: clippy
