version: '3.9'

services:
  ds:
    restart: always
    environment:
      _UVICORN__HOST: "0.0.0.0"
      _UVICORN__PORT: 8000
    volumes: []
    healthcheck:
      test: curl -f http://127.0.0.1:8000/health || exit 1
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1800M
    image: ghcr.io/teadove/fun-datascience:v2.0.3
