version: '3.9'

services:
  ds:
    restart: always
    environment: {}
    image: ghcr.io/teadove/fun-datascience:v1.0.22
    volumes: []
    healthcheck:
      test: curl -f http://127.0.0.1:8000/health || exit 1
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1800M
