version: '3.1'

services:
  ds:
    restart: always
    environment: {}
    build:
      context: .
      dockerfile: Dockerfile
    volumes: []
    healthcheck:
      test: curl -f http://127.0.0.1:8000/health || exit 1
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1400M
